### PR TITLE
Added pseudocode for Stock Span

### PR DESCRIPTION
**Pull request by codeboy5**

### CODE REVIEW

**Comment by codeboy5** [comment]
I accidentally named the folder stock instead of stack, should i make another pull request after correcting it?

**Comment by ghost** [comment]
I had already told you not to include the `pdf` file. (Plus, your PR shows 5 modified files instead of just 1).

Can you delete the fork and re-fork it. (And only modify a single file). Make a new PR.

**Comment by ghost** [comment]
You have a lot of `.ds_store` files in the commit. Please remove them by following this [link](https://hints.binaryage.com/how-to-remove-ds-store-files-from-a-git-repo/)

**Comment by ghost** [comment]
Normally, renaming a folder doesn't require a new pull request (just a new commit). However, here we need another pull request to resolve the conflict of `pdf` files.

**Comment by codeboy5** [comment]
Okay, I will make the necessary changes.

**Pull request closed without merging**
