### PR TITLE
Added pseudocode on Bubble Sort

### PR DESCRIPTION
**Pull request by omarr45**
I've added the Bubble Sort pseudocode

Please review and accept my PR
Thanks!

### CODE REVIEW

**Comment by omarr45** [comment]
Also,
Could you add the "hacktoberfest" label to the repository?
or maybe just add the "hacktoberfest-accepted" label to my PR

Thanks again!

**Comment by Just-A-Visitor** [comment]
@omarr45 I've already added the "Hacktoberfest" topic to the repository. If you still any face any issues with the PR, do let me know.

**Comment by omarr45** [comment]
I can see you've added the tag of Hacktober to the repo, but not the label.
See? there are no labels to this PR right now so it isn't counted for.
image
You shall find this button
image
it will allow you to add the label to my particular PR

You can check this link here
https://docs.github.com/en/free-pro-team@latest/github/managing-your-work-on-github/applying-labels-to-issues-and-pull-requests

Thanks !

**Comment by Just-A-Visitor** [comment]
Right. My bad. I've made the changes!

**Pull request merged**
